# Generated by Django 5.2.4 on 2025-07-22 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=100)),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(choices=[('action', 'Action'), ('drama', 'Drama'), ('comedy', 'Comedy'), ('romance', 'Romance'), ('thriller', 'Thriller'), ('documentary', 'Documentary'), ('animation', 'Animation')], db_index=True, max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='thumbnails/')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['category', 'created_at'], name='video_app_v_categor_598825_idx')],
            },
        ),
    ]
