# Generated by Django 5.2.4 on 2025-07-31 12:49

import django.core.validators
import video_app.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='duration_seconds',
            field=models.PositiveIntegerField(blank=True, help_text='Video duration in seconds', null=True),
        ),
        migrations.AddField(
            model_name='video',
            name='file_size_mb',
            field=models.PositiveIntegerField(blank=True, help_text='Original file size in MB', null=True),
        ),
        migrations.AddField(
            model_name='video',
            name='hls_directory',
            field=models.CharField(blank=True, help_text='Path to HLS files directory', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='video',
            name='original_file',
            field=models.FileField(blank=True, help_text='Original video file for processing (Max: 10GB)', null=True, upload_to='videos/original/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4', 'mov', 'avi', 'wmv', 'asf']), video_app.utils.validate_file_size]),
        ),
        migrations.AddField(
            model_name='video',
            name='processing_error',
            field=models.TextField(blank=True, help_text='Error message if processing failed', null=True),
        ),
        migrations.AddField(
            model_name='video',
            name='processing_progress',
            field=models.PositiveIntegerField(default=0, help_text='Processing progress in %', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='video',
            name='processing_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], db_index=True, default='pending', max_length=20),
        ),
    ]
