# Generated by Django 5.2.4 on 2025-08-08 08:57

import django.core.validators
import video_app.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_app', '0002_video_duration_seconds_video_file_size_mb_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='original_file',
            field=models.FileField(default='', help_text='Original video file for processing (Max: 10GB)', upload_to='videos/original/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4', 'mov', 'avi', 'wmv', 'asf']), video_app.utils.validate_file_size]),
            preserve_default=False,
        ),
    ]
